name: "Zephyr Zest_Core_nRF52832 CI/CD"

on:
  pull_request:
  workflow_dispatch:

jobs:
  board:
    uses: catie-aq/zephyr_workflows/.github/workflows/board.yml@main
    with:
      board: "zest_core_nrf52832"

    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}
